export const QUOTES = [
  "Disziplin schlägt Motivation, wenn die Lust fehlt.",
  "Der Körper erreicht, was der Geist glaubt.",
  "Jeder Satz zählt, auch der letzte, den du fast ausgelassen hättest.",
  "Fortschritt ist leise – zeig auf, komm wieder, wiederhole.",
  "Du musst nicht großartig sein, um anzufangen. Aber anfangen, um großartig zu werden.",
  "Schmerz ist vergänglich, Aufgeben ist für immer.",
  "Die beste Ausrede ist immer noch keine gute Ausrede.",
  "Kleine Schritte, jeden Tag – das ist der ganze Trick.",
  "Dein einziger Konkurrent ist die Version von dir von gestern.",
  "Comfort Zones bauen keine Muskeln.",
  "Es ist nie zu spät, heute anzufangen.",
  "Ausreden trainieren keine Muskeln.",
  "Der Weg ist unbequem – das Ergebnis nicht.",
  "Konsistenz schlägt Intensität, jedes Mal.",
  "Du wirst es nicht bereuen, trainiert zu haben.",
  "Stärke wächst nicht in der Komfortzone.",
  "Kein Regen, kein Regenbogen. Kein Training, kein Fortschritt.",
  "Zeig auf – der Rest ergibt sich.",
  "Der Unterschied zwischen Wunsch und Erfolg ist Handeln.",
  "Heute ist ein guter Tag für einen guten Tag.",
  "Es geht nicht um perfekt, es geht um besser als gestern.",
  "Müde ist ein Gefühl, kein Grund aufzuhören.",
  "Baue den Körper, der deine Ausreden trägt.",
  "Große Ziele beginnen mit einem einzigen Satz.",
  "Wer stehen bleibt, trainiert Stillstand.",
  "Schweiß ist einfach Fett, das weint.",
  "Der einzige schlechte Workout ist das, das nicht stattfand.",
  "Dein Warum muss stärker sein als deine Ausrede.",
  "Erfolg ist die Summe kleiner, wiederholter Anstrengungen.",
  "Du bist stärker, als deine letzte Wiederholung dir sagt.",
  "Mach es zur Gewohnheit, nicht zur Ausnahme.",
  "Der Spiegel lügt nicht, aber er wartet auch nicht.",
  "Wachstum passiert am Rand deiner Komfortzone.",
  "Ein Prozent besser jeden Tag reicht.",
  "Motivation bringt dich in Gang. Disziplin hält dich im Rennen.",
  "Trainiere wie jemand, der etwas beweisen will.",
  "Der beste Zeitpunkt war gestern. Der zweitbeste ist jetzt.",
  "Kraft ist ein Nebenprodukt von Konstanz.",
  "Verlier nie den Fortschritt aus den Augen, auch wenn er langsam ist.",
  "Jede Wiederholung bringt dich näher an dein Ziel.",
  "Was heute schwer ist, macht dich morgen stark.",
  "Champions werden gemacht, wenn keiner zuschaut.",
  "Deine Grenzen existieren meist nur in deinem Kopf.",
  "Bleib hungrig, bleib diszipliniert.",
  "Der Unterschied liegt in der letzten Wiederholung.",
  "Zweifel tötet mehr Träume als Scheitern je könnte.",
  "Investiere in dich selbst – es zahlt sich immer aus.",
  "Der Weg zur Stärke führt durch den Widerstand.",
  "Du kannst nicht zurück, aber du kannst weiter.",
  "Ausdauer ist Talent, das sich niemand gibt.",
  "Trainiere deinen Geist wie deinen Körper.",
  "Es ist dein Körper. Kein Ausreden-Museum.",
  "Fortschritt fühlt sich manchmal wie Stillstand an – bleib dran.",
  "Setze dich, wenn du müde bist. Gib nie auf.",
  "Jeder Meister war einmal ein Anfänger.",
  "Der Schmerz von heute ist die Stärke von morgen.",
  "Mach weiter, auch wenn niemand applaudiert.",
  "Disziplin ist die Brücke zwischen Zielen und Erfolg.",
  "Dein Körper hört auf deinen Geist. Trainiere beide.",
  "Nichts verändert sich, wenn nichts sich verändert.",
  "Sei stolz auf jeden kleinen Fortschritt.",
  "Wiederholung ist die Mutter der Meisterschaft.",
];

// Deterministic per-day index based on date
export function todayQuote(date = new Date()) {
  const dayNum = Math.floor(date.getTime() / 86400000);
  const idx = dayNum % QUOTES.length;
  return QUOTES[idx];
}
